### PR TITLE
Improved tool selection

### PR DESCRIPTION
**Pull request by Slord6**
I've updated bestHarvestTool to better select tools. It should, on average, choose the best available harvest tool now. Also, if there is no harvest tool associated with a block, eg `grass`, `leaves`, it will select a tool based on the block material

Edit: Worth noting that still does not cover enchanted tools

### CODE REVIEW

**Comment by Karang** [comment]
Thanks for this! It is indeed something that needs improvement.
We now have an accurate digTime() function in prismarine-block that could be used to implement the best tool selection.
Here is an example: https://github.com/Karang/mineflayer-pathfinder/blob/master/lib/movements.js#L108
This support the real speed modifier of the item as well as enchantments and player abilities and is guaranteed to be updated for future versions. Could you try to use it ?

Also, make sure you rebased on master, you seems to be missing some of the latest changes (look at the diff of the PR).

**Comment by Slord6** [comment]
Didn't see digTime, I'll have another look and refactor, that should make it more robust.

Not sure how I ended up with an old version, only forked the repo yesterday! Thanks for the heads up.

**Comment by Slord6** [comment]
I've made a complete mess of that feature branch somehow. Will close this PR and reimplement as per your above comment!

**Comment by Karang** [comment]
> I've made a complete mess of that feature branch somehow. Will close this PR and reimplement as per your above comment!

Thanks!

**Pull request closed without merging**
